version: "3.9"
services:
  synapse:
    image: homeserver-synapse:latest
    build:
      context: ./config
      dockerfile: Dockerfile.synapse
    volumes:
      - synapse-db:/data
    environment:
      SYNAPSE_SERVER_NAME: "localhost"
      SYNAPSE_REPORT_STATS: "no"
    # ports:
    #   - 8008:8008
    healthcheck:
      test: curl localhost:8008/health
      interval: 5s
      timeout: 10s
      retries: 5
    labels:
      - "org.homeserver=true"
    restart: unless-stopped
  element:
    image: vectorim/element-web:latest
    restart: unless-stopped
  nginx:
    image: homeserver-nginx:latest
    build:
      context: ./config
      dockerfile: Dockerfile.nginx
    ports:
      - "8008:80"
    depends_on:
      synapse:
        condition: service_healthy
    expose:
      - "nginx:80"
    restart: unless-stopped
    environment:
      MATRIX_SERVER_NAME: localhost
      MATRIX_INTERNAL_SERVER_URI: synapse:8008
      MATRIX_SERVER_FQDN: http://localhost:8008

volumes:
  synapse-db:

networks:
  default:
    name: fractal-matrix-network
    external: true
