# syntax=docker/dockerfile:1
FROM python:3.11.4

ENV PYTHONUNBUFFERED=1
ENV PYTHON_BIN=python

WORKDIR /code

# install fractal-database from pypi
RUN pip install fractal-database

COPY fractal_database_matrix /code/fractal_database_matrix
COPY pyproject.toml README.md /code/

# install modules
RUN pip3 install -e /code[dev]

COPY tests /code/tests
COPY .coveragerc conftest.py pytest.ini /code/

COPY test-config /test-config
COPY Makefile /code

ENTRYPOINT [ "/test-config/entrypoint.sh" ]
