# Generated by Django 4.2.4 on 2023-11-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fractal_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixReplicationTarget',
            fields=[
                ('replicationtarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fractal_database.replicationtarget')),
                ('access_token', models.CharField(default=None, max_length=255)),
                ('homeserver', models.CharField(default=None, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('fractal_database.replicationtarget',),
        ),
    ]
